import { css } from "lit";
export const styles = css`
  :host { display:block; min-height:100vh; color:var(--primary-text-color,#213832); background:var(--primary-background-color,#f6f7f4); font-family:var(--paper-font-body1_-_font-family,Inter,system-ui,sans-serif); --accent:#326753; --muted:var(--secondary-text-color,#718078); --surface:var(--ha-card-background,var(--card-background-color,#fff)); --line:var(--divider-color,#e3e9e3); }
  * { box-sizing:border-box; } button,input,select { font:inherit; } button { cursor:pointer; } button:disabled { opacity:.5; cursor:wait; } button:focus-visible,input:focus-visible,select:focus-visible { outline:3px solid #a2cab5; outline-offset:3px; }
  .shell { max-width:1260px; margin:auto; padding:36px 42px 72px; } header { display:flex; align-items:center; justify-content:space-between; gap:20px; margin-bottom:28px; }
  .brand { display:flex; gap:14px; align-items:center; } .logo { width:48px; height:48px; border-radius:14px; background:var(--accent); color:#fff; display:grid; place-items:center; }
  h1 { margin:0; font-size:25px; font-weight:650; letter-spacing:-.8px; } .subtitle { margin:5px 0 0; color:var(--muted); font-size:13px; } .pill { display:inline-flex; align-items:center; gap:7px; border-radius:30px; padding:7px 11px; background:#e6f0e9; color:#326753; font-size:11px; font-weight:600; }
  svg { width:20px; height:20px; fill:none; stroke:currentColor; stroke-width:1.7; stroke-linecap:round; stroke-linejoin:round; } .logo svg { width:26px; height:26px; }
  nav { display:flex; gap:7px; border-bottom:1px solid var(--line); padding-bottom:12px; margin-bottom:28px; overflow-x:auto; } nav button { flex-shrink:0; display:flex; align-items:center; gap:8px; border:0; border-radius:9px; background:transparent; color:var(--muted); padding:11px 14px; font-size:13px; font-weight:550; } nav button.active { background:var(--accent); color:#fff; } nav svg { width:17px; height:17px; }
  .stats { display:grid; grid-template-columns:repeat(3,1fr); gap:17px; margin-bottom:26px; } .stat { display:flex; gap:16px; align-items:center; border:1px solid var(--line); border-radius:13px; background:var(--surface); padding:23px; } .stat-icon { width:43px; height:43px; display:grid; place-items:center; background:#eef3ee; color:#4b705a; border-radius:12px; } .stat:nth-child(2) .stat-icon { background:#f4eee1; color:#9b7738; } .stat:nth-child(3) .stat-icon { background:#eef0f7; color:#75809f; } .stat strong { display:block; font-size:28px; line-height:1; font-weight:600; } .stat span { color:var(--muted); font-size:12px; display:block; margin-top:8px; }
  .hero { display:flex; justify-content:space-between; align-items:center; gap:24px; padding:29px 32px; border-radius:14px; background:#e8eee4; color:#244837; margin-bottom:32px; position:relative; overflow:hidden; } .hero h2 { font-size:22px; margin:0 0 8px; letter-spacing:-.5px; } .hero p { margin:0; color:#647d69; font-size:13px; } .hero svg.big { width:85px; height:85px; opacity:.12; position:absolute; right:225px; top:10px; }
  .hero > svg { display:none; }
  .primary,.secondary,.danger,.icon-button { display:inline-flex; justify-content:center; align-items:center; gap:8px; border-radius:9px; padding:11px 15px; border:1px solid transparent; font-size:13px; font-weight:550; white-space:nowrap; } .primary { background:var(--accent); color:#fff; } .secondary { border-color:var(--line); background:var(--surface); color:var(--primary-text-color,#213832); } .danger { color:#a54538; background:transparent; border-color:#e8c6bf; } .icon-button { padding:8px; color:var(--muted); background:transparent; } .text-button { border:0; background:transparent; color:var(--accent); font-size:12px; padding:8px; }
  .section-head { display:flex; justify-content:space-between; align-items:center; gap:15px; margin-bottom:20px; } h2 { font-size:18px; font-weight:600; margin:0; letter-spacing:-.3px; } .caption { color:var(--muted); font-size:12px; line-height:1.6; margin-top:8px; } .grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:20px; } .camera-grid { grid-template-columns:repeat(2,minmax(0,1fr)); }
  .card { border:1px solid var(--line); border-radius:13px; background:var(--surface); overflow:hidden; } .card-body { padding:21px; } .card h3 { font-size:15px; margin:0 0 8px; font-weight:600; } .card-top { display:flex; align-items:center; gap:12px; margin-bottom:17px; } .card-top .stat-icon { width:39px; height:39px; } .card-actions { display:flex; align-items:center; gap:8px; margin-top:18px; flex-wrap:wrap; } .card-actions .secondary { flex:1; } .path { display:block; color:var(--muted); font-size:11px; overflow-wrap:anywhere; margin:8px 0; font-family:ui-monospace,monospace; } .metadata { display:flex; gap:12px; flex-wrap:wrap; color:var(--muted); font-size:11px; margin-top:12px; } .badge { font-size:10px; padding:4px 8px; border-radius:6px; background:#e9f0e9; color:#456d52; } .badge.running,.badge.queued { background:#faf0d9; color:#8a6d26; } .badge.failed,.badge.interrupted { background:#f9e9e4; color:#a2523f; } .badge.cancelled { background:#eee; color:#777; }
  .video-cover { height:150px; position:relative; overflow:hidden; display:grid; place-items:center; background:linear-gradient(145deg,#bccdb2 0%,#8faa99 48%,#486b5c 100%); color:#fff; border:0; width:100%; } .video-cover::before { content:""; position:absolute; width:120%; height:90%; border-radius:50%; background:#46684f; transform:rotate(-15deg); top:72%; left:-15%; opacity:.6; } .video-cover::after { content:""; position:absolute; width:75%; height:100%; border-radius:50%; background:#314e3e; top:65%; right:-17%; opacity:.5; } .video-cover .play { width:42px; height:42px; border:1px solid #ffffff80; border-radius:50%; background:#ffffff20; backdrop-filter:blur(3px); display:grid; place-items:center; z-index:1; } .video-cover .cover-label { position:absolute; top:13px; left:13px; font-size:10px; padding:5px 8px; background:#ffffffd9; color:#355844; border-radius:5px; } .video-cover .cover-duration { position:absolute; bottom:12px; right:12px; font-size:10px; padding:4px 6px; background:#203b3399; border-radius:4px; z-index:1; }
  .empty { border:1px dashed var(--line); padding:52px 22px; border-radius:13px; text-align:center; color:var(--muted); } .empty svg { width:40px; height:40px; color:#90a593; margin-bottom:16px; } .empty h3 { color:var(--primary-text-color,#213832); font-size:17px; font-weight:550; margin:0 0 10px; } .empty p { font-size:13px; max-width:430px; margin:0 auto 20px; line-height:1.6; }
  .toolbar { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:20px; } .toolbar select { min-width:170px; width:auto; } .schedule-card { padding:24px; margin-bottom:16px; } .schedule-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:22px; margin:22px 0; } .schedule-block { padding:17px; border-radius:10px; background:var(--primary-background-color,#f6f7f4); } .schedule-block label.toggle { display:flex; align-items:center; justify-content:space-between; gap:10px; margin-bottom:12px; } .schedule-block input[type=checkbox] { width:17px; height:17px; accent-color:var(--accent); }
  .job { border:1px solid var(--line); border-radius:12px; padding:21px; margin-bottom:13px; background:var(--surface); } .job-head { display:flex; gap:12px; align-items:center; justify-content:space-between; } .job h3 { font-size:14px; margin:0 0 6px; } .job p { margin:0; color:var(--muted); font-size:12px; } progress { width:100%; height:7px; display:block; accent-color:var(--accent); margin:17px 0 11px; } details { font-size:12px; color:var(--muted); margin-top:13px; } details ul { padding-left:20px; } details li { margin-bottom:6px; overflow-wrap:anywhere; }
  .settings-card { padding:27px; max-width:800px; } .form-grid { display:grid; grid-template-columns:1fr 1fr; gap:18px; } .field { display:flex; flex-direction:column; gap:8px; } .field.full { grid-column:1/-1; } label { font-size:12px; font-weight:550; } input,select { border:1px solid var(--line); border-radius:8px; padding:11px 12px; background:var(--surface); color:var(--primary-text-color,#213832); width:100%; font-size:13px; min-width:0; } input[type=checkbox] { width:auto; } .help { color:var(--muted); font-size:11px; line-height:1.6; margin:0; } .form-actions { display:flex; justify-content:flex-end; gap:9px; margin-top:24px; } .spaced { margin-top:24px; }
  dialog { border:1px solid var(--line); border-radius:16px; background:var(--surface); color:var(--primary-text-color,#213832); max-width:660px; width:calc(100% - 32px); padding:27px; box-shadow:0 16px 80px #182b3330; } dialog::backdrop { background:#16302665; backdrop-filter:blur(2px); } dialog .section-head { margin-bottom:23px; } .player-dialog { max-width:950px; } video { display:block; width:100%; border-radius:9px; max-height:65vh; background:#17271f; } .scan-result { background:#edf4ed; color:#305c40; border-radius:9px; padding:16px; margin-top:17px; font-size:12px; } .scan-result code { display:block; font-size:10px; margin-top:6px; overflow-wrap:anywhere; } .alert { color:#9f4937; background:#fff0ea; border-radius:9px; padding:12px 15px; font-size:12px; margin-bottom:20px; overflow-wrap:anywhere; } .notice { color:#42624b; background:#e7f0e5; border-radius:9px; padding:12px 15px; font-size:12px; margin-bottom:20px; }
  footer { display:flex; align-items:center; justify-content:space-between; color:var(--muted); font-size:10px; margin-top:42px; } footer svg { width:13px; height:13px; } .footer-brand { display:flex; gap:6px; align-items:center; } .loading { text-align:center; padding:90px 20px; color:var(--muted); } .menu-button { display:none; }
  @media(max-width:900px) { .shell { padding:25px; } .grid { grid-template-columns:repeat(2,minmax(0,1fr)); } .schedule-grid { gap:12px; } .hero svg.big { display:none; } }
  @media(max-width:600px) { .shell { padding:20px 16px 40px; } .menu-button { display:inline-flex; } .brand { gap:10px; } .logo { width:40px; height:40px; } h1 { font-size:22px; } header>.pill { display:none; } .stats { gap:8px; } .stat { display:block; padding:14px 10px; } .stat-icon { width:30px; height:30px; margin-bottom:12px; } .stat strong { font-size:24px; } .stat span { font-size:10px; line-height:1.5; } .hero { padding:22px; display:block; } .hero h2 { font-size:19px; } .hero button { margin-top:18px; } .grid,.camera-grid,.schedule-grid { grid-template-columns:1fr; } nav { gap:3px; } nav button { padding:10px 11px; } .form-grid { grid-template-columns:1fr; } .field.full { grid-column:auto; } .job-head { flex-wrap:wrap; } dialog { padding:21px; } footer span:last-child { max-width:140px; text-align:right; } }
`;
